FROM golang:1.23-alpine AS builder

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Expose the port the application will run on
EXPOSE 8083

# Set PATH to include Go binaries
ENV PATH="$PATH:/go/bin"

# Run the application with air
CMD ["air"]
