// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.19.6
// source: spec/apiMessages.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Arr           []int64                `protobuf:"varint,3,rep,packed,name=arr,proto3" json:"arr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortingRequest) Reset() {
	*x = SortingRequest{}
	mi := &file_spec_apiMessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortingRequest) ProtoMessage() {}

func (x *SortingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_apiMessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortingRequest.ProtoReflect.Descriptor instead.
func (*SortingRequest) Descriptor() ([]byte, []int) {
	return file_spec_apiMessages_proto_rawDescGZIP(), []int{0}
}

func (x *SortingRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SortingRequest) GetArr() []int64 {
	if x != nil {
		return x.Arr
	}
	return nil
}

type SoritingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	SortedArr     []int64                `protobuf:"varint,2,rep,packed,name=sortedArr,proto3" json:"sortedArr,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoritingResponse) Reset() {
	*x = SoritingResponse{}
	mi := &file_spec_apiMessages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoritingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoritingResponse) ProtoMessage() {}

func (x *SoritingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_apiMessages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoritingResponse.ProtoReflect.Descriptor instead.
func (*SoritingResponse) Descriptor() ([]byte, []int) {
	return file_spec_apiMessages_proto_rawDescGZIP(), []int{1}
}

func (x *SoritingResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SoritingResponse) GetSortedArr() []int64 {
	if x != nil {
		return x.SortedArr
	}
	return nil
}

func (x *SoritingResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_spec_apiMessages_proto protoreflect.FileDescriptor

var file_spec_apiMessages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0e, 0x53, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x03, 0x61, 0x72, 0x72, 0x22, 0x5c, 0x0a, 0x10, 0x53, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x41, 0x72, 0x72, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x41, 0x72, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_apiMessages_proto_rawDescOnce sync.Once
	file_spec_apiMessages_proto_rawDescData = file_spec_apiMessages_proto_rawDesc
)

func file_spec_apiMessages_proto_rawDescGZIP() []byte {
	file_spec_apiMessages_proto_rawDescOnce.Do(func() {
		file_spec_apiMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_apiMessages_proto_rawDescData)
	})
	return file_spec_apiMessages_proto_rawDescData
}

var file_spec_apiMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spec_apiMessages_proto_goTypes = []any{
	(*SortingRequest)(nil),   // 0: SortingRequest
	(*SoritingResponse)(nil), // 1: SoritingResponse
}
var file_spec_apiMessages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spec_apiMessages_proto_init() }
func file_spec_apiMessages_proto_init() {
	if File_spec_apiMessages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_apiMessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_apiMessages_proto_goTypes,
		DependencyIndexes: file_spec_apiMessages_proto_depIdxs,
		MessageInfos:      file_spec_apiMessages_proto_msgTypes,
	}.Build()
	File_spec_apiMessages_proto = out.File
	file_spec_apiMessages_proto_rawDesc = nil
	file_spec_apiMessages_proto_goTypes = nil
	file_spec_apiMessages_proto_depIdxs = nil
}
